"use client";

import {
  BabyIcon,
  BarbellIcon,
  BathtubIcon,
  BedIcon,
  BicycleIcon,
  CampfireIcon,
  CarIcon,
  CoffeeIcon,
  CookingPotIcon,
  DesktopIcon,
  DropIcon,
  FanIcon,
  FireIcon,
  FirstAidIcon,
  FlowerIcon,
  ForkKnifeIcon,
  GaugeIcon,
  HairDryerIcon,
  LockIcon,
  MountainsIcon,
  OvenIcon,
  PawPrintIcon,
  PlantIcon,
  SnowflakeIcon,
  SparkleIcon,
  SwimmingPoolIcon,
  TelevisionIcon,
  ThermometerIcon,
  TShirtIcon,
  UmbrellaIcon,
  WavesIcon,
  WashingMachineIcon,
  WifiHighIcon,
  WindIcon,
  WheelchairIcon,
  type Icon,
} from "@phosphor-icons/react";

/** Icons admins can assign to amenities. Keys are stored in `Amenity.icon`. */
export const AMENITY_ICONS: Record<string, Icon> = {
  WifiHigh: WifiHighIcon,
  Snowflake: SnowflakeIcon,
  Fire: FireIcon,
  Thermometer: ThermometerIcon,
  SwimmingPool: SwimmingPoolIcon,
  Car: CarIcon,
  CookingPot: CookingPotIcon,
  Oven: OvenIcon,
  ForkKnife: ForkKnifeIcon,
  Coffee: CoffeeIcon,
  WashingMachine: WashingMachineIcon,
  TShirt: TShirtIcon,
  Television: TelevisionIcon,
  Desktop: DesktopIcon,
  Bathtub: BathtubIcon,
  HairDryer: HairDryerIcon,
  Bed: BedIcon,
  Baby: BabyIcon,
  PawPrint: PawPrintIcon,
  Wheelchair: WheelchairIcon,
  Mountains: MountainsIcon,
  Waves: WavesIcon,
  Flower: FlowerIcon,
  Plant: PlantIcon,
  Campfire: CampfireIcon,
  Bicycle: BicycleIcon,
  Barbell: BarbellIcon,
  Umbrella: UmbrellaIcon,
  Lock: LockIcon,
  FirstAid: FirstAidIcon,
  Drop: DropIcon,
  Fan: FanIcon,
  Wind: WindIcon,
  Gauge: GaugeIcon,
  Sparkle: SparkleIcon,
};

export function AmenityIcon({ name, size = 20, className }: { name: string; size?: number; className?: string }) {
  const Component = AMENITY_ICONS[name] ?? SparkleIcon;
  return <Component size={size} className={className} aria-hidden />;
}
