// Entry point of the Cloudflare Worker: the Next.js app built by OpenNext, plus the scheduled task.
// `.open-next/worker.js` is generated by `npm run cf:build`.
import { default as handler } from "../.open-next/worker.js";

const IMMUTABLE = "public, max-age=31536000, immutable";
/** Optimised variants (one per source, width, quality and format) are kept in the MEDIA bucket under this prefix. */
const IMAGE_CACHE_PREFIX = "_image-cache/";

const worker = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (request.method === "GET" || request.method === "HEAD") {
      if (url.pathname === "/_next/image") return optimizedImage(request, url, env, ctx);
      if (url.pathname.startsWith("/media/properties/") && env.MEDIA) return mediaObject(env.MEDIA, url.pathname);
    }
    return handler.fetch(request, env, ctx);
  },

  /**
   * Cron Trigger (wrangler.jsonc → triggers.crons): runs the same housekeeping as GET /api/cron
   * (expire unpaid holds, finish stays, reminders, Airbnb/iCal sync, email retries) through the app.
   */
  async scheduled(controller, env, ctx) {
    const request = new Request(new URL("/api/cron", env.APP_URL), {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      throw new Error(`Scheduled run (${controller.cron}) failed: ${response.status} ${await response.text()}`);
    }
    console.log(`Scheduled run (${controller.cron}):`, await response.text());
  },
};

export default worker;

/**
 * Property photos straight from R2, streamed (no trip through the Next.js server). Keys are random
 * UUIDs that never change, so browsers and the CDN may keep them for a year.
 */
async function mediaObject(bucket, pathname) {
  const object = await bucket.get(decodeURIComponent(pathname.slice("/media/".length)));
  if (!object) return new Response(null, { status: 404 });
  return new Response(object.body, {
    headers: {
      "Content-Type": object.httpMetadata?.contentType ?? "application/octet-stream",
      "Cache-Control": IMMUTABLE,
      ETag: object.httpEtag,
      "X-Content-Type-Options": "nosniff",
    },
  });
}

/**
 * next/image on Cloudflare. OpenNext validates the request and resizes with the Images binding, but
 * on its own it caches nothing (every view fetched the original and re-encoded it: 1-2 s per photo)
 * and it looks up same-origin sources in the static assets, where photos uploaded to R2 (/media/…)
 * do not exist. Here each variant is produced once, stored in R2, and served with a long cache life.
 */
async function optimizedImage(request, url, env, ctx) {
  const accept = request.headers.get("accept") ?? "";
  // Same negotiation as OpenNext (formats in next.config.ts: AVIF, then WEBP, else the original type).
  const format = accept.includes("image/avif") ? "avif" : accept.includes("image/webp") ? "webp" : "original";
  const params = url.searchParams;
  const key = IMAGE_CACHE_PREFIX + (await sha256(`${params.get("url")}|${params.get("w")}|${params.get("q")}|${format}`));

  const cached = await env.MEDIA?.get(key).catch(() => null);
  if (cached) {
    return new Response(cached.body, {
      headers: { ...cached.customMetadata, "Content-Type": cached.httpMetadata?.contentType ?? "image/webp", Vary: "Accept", "Cache-Control": IMMUTABLE },
    });
  }

  const response = await handler.fetch(request, { ...env, ASSETS: assetsWithMedia(env) }, ctx);
  const contentType = response.headers.get("content-type") ?? "";
  if (!response.ok || !contentType.startsWith("image/")) return response;

  const body = await response.arrayBuffer();
  const headers = new Headers(response.headers);
  headers.set("Cache-Control", IMMUTABLE);
  if (env.MEDIA) {
    const customMetadata = {};
    for (const name of ["Content-Disposition", "Content-Security-Policy"]) {
      const value = response.headers.get(name);
      if (value) customMetadata[name] = value;
    }
    ctx.waitUntil(env.MEDIA.put(key, body, { httpMetadata: { contentType }, customMetadata }).catch((error) => console.error("[image-cache]", error)));
  }
  return new Response(body, { status: response.status, headers });
}

/** The static assets binding, plus the R2 photos (/media/properties/…) as image sources. */
function assetsWithMedia(env) {
  return {
    fetch(input, init) {
      const pathname = new URL(input instanceof Request ? input.url : input).pathname;
      if (pathname.startsWith("/media/properties/") && env.MEDIA) return mediaObject(env.MEDIA, pathname);
      return env.ASSETS.fetch(input, init);
    },
  };
}

async function sha256(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}
