// Entry point of the Cloudflare Worker: the Next.js app built by OpenNext, plus the scheduled task.
// `.open-next/worker.js` is generated by `npm run cf:build`.
import { default as handler } from "../.open-next/worker.js";

const worker = {
  fetch: handler.fetch,

  /**
   * Cron Trigger (wrangler.jsonc → triggers.crons): runs the same housekeeping as GET /api/cron
   * (expire unpaid holds, finish stays, reminders, Airbnb/iCal sync, email retries) through the app.
   */
  async scheduled(controller, env, ctx) {
    const request = new Request(new URL("/api/cron", env.APP_URL), {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      throw new Error(`Scheduled run (${controller.cron}) failed: ${response.status} ${await response.text()}`);
    }
    console.log(`Scheduled run (${controller.cron}):`, await response.text());
  },
};

export default worker;
